"""sync users and symbols schema

Revision ID: 27f8f3ac68c7
Revises: 3b8d5e2a7c19
Create Date: 2026-05-26 21:23:34.746517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27f8f3ac68c7'
down_revision: Union[str, None] = '3b8d5e2a7c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # symbols: 唯一约束 → 唯一索引（语义等价，统一风格）
    op.drop_constraint(op.f('symbols_symbol_key'), 'symbols', type_='unique')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)

    # users: 补 ORM 早期遗漏的两列；server_default 保证已有行不冲突
    op.add_column(
        'users',
        sa.Column('password_hash', sa.String(length=255), nullable=False, server_default=''),
    )
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=False)
    op.create_unique_constraint(op.f('symbols_symbol_key'), 'symbols', ['symbol'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
