"""add sim_equity_snapshots

Revision ID: 3afb46c74f15
Revises: 63655e556d5b
Create Date: 2026-06-16 21:12:47.940156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3afb46c74f15'
down_revision: Union[str, None] = '63655e556d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('total_asset', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dt', name='uq_equity_user_dt')
    )
    op.create_index(op.f('ix_sim_equity_snapshots_dt'), 'sim_equity_snapshots', ['dt'], unique=False)
    op.create_index(op.f('ix_sim_equity_snapshots_user_id'), 'sim_equity_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_equity_snapshots_user_id'), table_name='sim_equity_snapshots')
    op.drop_index(op.f('ix_sim_equity_snapshots_dt'), table_name='sim_equity_snapshots')
    op.drop_table('sim_equity_snapshots')
    # ### end Alembic commands ###
