"""add watchlists and ai_alerts

Revision ID: 3b597a00cb62
Revises: a332786c9ac0
Create Date: 2026-05-27 01:05:16.093052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b597a00cb62'
down_revision: Union[str, None] = 'a332786c9ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False, server_default='info'),
    sa.Column('signal', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False, server_default=''),
    sa.Column('snapshot', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")),
    sa.Column('acked', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_alerts_acked'), 'ai_alerts', ['acked'], unique=False)
    op.create_index(op.f('ix_ai_alerts_created_at'), 'ai_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_alerts_level'), 'ai_alerts', ['level'], unique=False)
    op.create_index(op.f('ix_ai_alerts_symbol'), 'ai_alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_ai_alerts_user_id'), 'ai_alerts', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=False, server_default=''),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_user_symbol')
    )
    op.create_index(op.f('ix_watchlists_symbol'), 'watchlists', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_symbol'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_ai_alerts_user_id'), table_name='ai_alerts')
    op.drop_index(op.f('ix_ai_alerts_symbol'), table_name='ai_alerts')
    op.drop_index(op.f('ix_ai_alerts_level'), table_name='ai_alerts')
    op.drop_index(op.f('ix_ai_alerts_created_at'), table_name='ai_alerts')
    op.drop_index(op.f('ix_ai_alerts_acked'), table_name='ai_alerts')
    op.drop_table('ai_alerts')
    # ### end Alembic commands ###
