"""add param_sweep_jobs

Revision ID: 4b8796f56890
Revises: b1c2d3e4f5a6
Create Date: 2026-06-05 21:03:22.006259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b8796f56890'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('param_sweep_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('class_name', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('param_grid', sa.JSON(), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('init_capital', sa.Float(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_param_sweep_jobs_user_id'), 'param_sweep_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_param_sweep_jobs_user_id'), table_name='param_sweep_jobs')
    op.drop_table('param_sweep_jobs')
    # ### end Alembic commands ###
