"""add period and oos_split to backtest jobs

Revision ID: 63655e556d5b
Revises: d4845eee9740
Create Date: 2026-06-12 21:48:11.588922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '63655e556d5b'
down_revision: Union[str, None] = 'd4845eee9740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_jobs', sa.Column('period', sa.String(length=8), server_default='1d', nullable=False))
    op.add_column('param_sweep_jobs', sa.Column('period', sa.String(length=8), server_default='1d', nullable=False))
    op.add_column('param_sweep_jobs', sa.Column('oos_split', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('param_sweep_jobs', 'oos_split')
    op.drop_column('param_sweep_jobs', 'period')
    op.drop_column('backtest_jobs', 'period')
    # ### end Alembic commands ###
