"""add notify rules and logs

Revision ID: a332786c9ac0
Revises: 27f8f3ac68c7
Create Date: 2026-05-27 00:54:52.177318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a332786c9ac0'
down_revision: Union[str, None] = '27f8f3ac68c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('match_types', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    sa.Column('match_filters', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")),
    sa.Column('channels', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    sa.Column('feishu_webhook', sa.Text(), nullable=False, server_default=''),
    sa.Column('feishu_secret', sa.String(length=128), nullable=False, server_default=''),
    sa.Column('quiet_hours', sa.String(length=16), nullable=False, server_default=''),
    sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_rules_user_id'), 'notify_rules', ['user_id'], unique=False)
    op.create_table('notify_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")),
    sa.Column('success', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('error_msg', sa.Text(), nullable=False, server_default=''),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['notify_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_logs_created_at'), 'notify_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_notify_logs_event_type'), 'notify_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_notify_logs_rule_id'), 'notify_logs', ['rule_id'], unique=False)
    op.create_index(op.f('ix_notify_logs_user_id'), 'notify_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notify_logs_user_id'), table_name='notify_logs')
    op.drop_index(op.f('ix_notify_logs_rule_id'), table_name='notify_logs')
    op.drop_index(op.f('ix_notify_logs_event_type'), table_name='notify_logs')
    op.drop_index(op.f('ix_notify_logs_created_at'), table_name='notify_logs')
    op.drop_table('notify_logs')
    op.drop_index(op.f('ix_notify_rules_user_id'), table_name='notify_rules')
    op.drop_table('notify_rules')
    # ### end Alembic commands ###
