"""add sync_logs

Revision ID: b3100277d354
Revises: 4b8796f56890
Create Date: 2026-06-07 23:57:59.785529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b3100277d354'
down_revision: Union[str, None] = '4b8796f56890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_date', sa.String(length=10), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period', name='uq_sync_logs_symbol_period')
    )
    op.create_index(op.f('ix_sync_logs_symbol'), 'sync_logs', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_symbol'), table_name='sync_logs')
    op.drop_table('sync_logs')
    # ### end Alembic commands ###
