"""add sim_accounts

Revision ID: d4845eee9740
Revises: b2cf008fad46
Create Date: 2026-06-11 23:13:43.675336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4845eee9740'
down_revision: Union[str, None] = 'b2cf008fad46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('init_capital', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_accounts_user_id'), 'sim_accounts', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_accounts_user_id'), table_name='sim_accounts')
    op.drop_table('sim_accounts')
    # ### end Alembic commands ###
